---
name: Check domainname (PR_target)
on: [pull_request_target]
jobs:
  build:
    name: Find substring job
    runs-on: ubuntu-latest
    steps:
      - name: start deployment
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: staging
          # deployment_id: ${{ github.event.deployment.id }}
          ref: "refs/pull/${{ github.event.number }}/head"
          desc: "depl_id: ${{ github.event.deployment.id }}, ref_id: ${{ github.head_ref }}"
          log_args: true
          
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Run bash script
        shell: bash
        run: sh -c .github/actions/find-substring/find-substring.sh

      - name: Create Commit Comment, if fail
        if: ${{ failure() }}
        uses: peter-evans/commit-comment@v1
        with:
          body: Domain name should not be used in the source code

      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          
